### ISSUE TITLE
"Магические" дополнительные переводы в переводчике.

### ISSUE THREAD

**Issue by WhitePulsar** [Kazbek/StarSectorLocalizer#14]
/Languages/ru/starsector-core/data/strings/descriptions.csv.translation.json
[https://github.com/Kazbek/StarSectorLocalizer/blob/main/Translation/Languages/ru/starsector-core/data/strings/descriptions.csv.translation.json](url)
411 строка. 
В "значении" скопирован "ключ", из за этого переводчик даже после перевода указывает, что сделал [1] изменение.

- [x] Перевести или или указать null

**Comment by Kazbek** [comment]
Переведено
https://github.com/Kazbek/StarSectorLocalizer/commit/63748a2d8770491debbb4ece6ffaacbca5f38ac1
